main :: IO ()
  {- main 
     RETURNS: ... 
     SIDE EFFECTS: 
     EXAMPLES:
   -}

function :: ... -> ...
  {- empty function x
     RETURNS: ...
   -}
function = undefined 
   
function :: ... -> ...
  {- empty function x
     RETURNS: ...
   -}
function = undefined 
   
function :: ... -> ...
  {- empty function x
     RETURNS: ...
   -}
function = undefined 

function :: ... -> ...
  {- empty function x
     RETURNS: ...
   -}
function = undefined 

function :: ... -> ...
  {- empty function x
     RETURNS: ...
   -}
function = undefined 
